server:
  port: 9595
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/gateway_db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
