server:
  port: 9090

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
      url: jdbc:mysql://localhost:3306/payment_db
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: PAYMENT-SERVICE